default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - |
      if [ -z "$NGINX_USER" ] || [ -z "$NGINX_PASS" ]; then
        echo "Error: Required variables NGINX_USER and/or NGINX_PASS are not set"
        exit 1
      fi
    - docker info


stages:
  - build
  - test
  # - deploy
  # - cleanup

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  NGINX_USER: $NGINX_USER  
  NGINX_PASS: $NGINX_PASS

build:
  stage: build
  script:
    - docker-compose up

test:
  stage: test
  script:
    - docker-compose up -d
    - npm install
    # Pass CI variables directly to the test command
    - NGINX_USER=$NGINX_USER NGINX_PASS=$NGINX_PASS npm test
    
  rules:
    - if: '$CI_COMMIT_BRANCH == "project"'
