services:
  service1:  
    image: risha/service1  
    depends_on:
      - service2  
    build:
      dockerfile: Dockerfile  
      context:  ./service1  
    deploy:
      replicas: 3 # Creating 3 instances of service1
    networks:
      - backend  # Connects the service to the "backend" network
    environment:
      - SERVICE2_BASE_URL=http://service2:8200
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    build: ./nginx
    ports:
      - "8198:8198" # Only exposing port 8198
    networks:
      - backend
    depends_on:
      - service1
    
  service2:  
      image: risha/service2  
      build:
        dockerfile: Dockerfile  
        context: ./service2  
      networks:
        - backend  # Connects the service to the "backend" network

networks:
  backend:  # Defines a custom Docker network named "backend" for communication between services
  # name: "${CI_PROJECT_NAME}_backend"
  # driver: bridge