services:
  test-runner:
    image: node:20
    depends_on:
      - nginx
    networks:
      - devops-course_backend
    working_dir: /app/tests
    volumes:
      - ./tests:/app/tests
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NGINX_USER
      - NGINX_PASS
      - IS_DOCKER=1
    command: >
      bash -c "npm install && npm test"

networks:
  devops-course_backend:
    external: true  # Use the existing network